### PR TITLE
Travis to publish to Hex.pm (via rebar3)

### PR DESCRIPTION
**Pull request by andreineculau**
follow-up to #14 and https://github.com/for-GET/jesse/issues/69#issuecomment-408037319

* [ ] `make ct` fails with unclear message `*** CT 2018-07-26 18:02:00.412 *** Suite Hook
Failed to start a CTH: exit:{noproc, [{gen,do_for_proc,2,...`

PS: limited and very sparse time on my hands (parental leave), so opening up a PR for feedback. Those who are interested and have some time, please help me out with the above checklist

---
This change is [Reviewable](https://reviewable.io/reviews/for-get/jesse/71)

### CODE REVIEW

**Comment by andreineculau** [comment]
poke @benoitc @Licenser

**Comment by benoitc** [comment]
@andreineculau makes sure to use latest rebar3 it should fix the issue

**Comment by andreineculau** [comment]
@benoitc great. I will try it out, i did a "wget s3://.../rebar3" but i never checked what's the latest

**Comment by mrallen1** [comment]
Has there been any more time to look into this?

**Comment by paulo-ferraz-oliveira** [comment]
https://github.com/for-GET/jesse/pull/84#issuecomment-841197822 potentially applies here, too.

**Pull request closed without merging**
