### PR TITLE
Travis to publish to Hex.pm (via rebar3)

### PR DESCRIPTION
**Pull request by afhole**
Re. https://github.com/for-GET/jesse/pull/71
I have made some additions to the Hex/Rebar3 support and the Travis builds are now passing.
Hopefully this is sufficient to allow Travis to push releases to Hex.

I am not certain if this is now ready to merge but it looks good to my untrained eye - I welcome any feedback.
Cheers

### CODE REVIEW

**Comment by seriyps** [comment]
@andreineculau ping :-)

**Comment by seriyps** [comment]
@andreineculau ping2. I could merge this, but someone needs to set-up travis to provide API keys

**Comment by andreineculau** [comment]
"ETA: this weekend" my ass 😂 sorry about this.
I would have thought that you have the necessary permissions to change Travis API Keys as well @seriyps (since you can merge the PR).

I setup `rebar3 hex` (btw why do we monkeypatch rebar.config on the fly, rather than commit the change https://github.com/for-GET/jesse/pull/84/files#diff-4b6714920c2cdbde45f050a1d1b4af1bR12-R14 ?) and created keys, but I have no clue as to how to retrieve the key `./rebar3 hex key ?` because I'm expecting that I don't actually have to expose the key in `~/.hex/hex.config` to travis, or ?

**Comment by afhole** [comment]
I believe the monkey patching is for Travis's `~/.config/rebar3/rebar.config` rather than the one from this repo, to enable the Hex plugin. Sorry if I have misunderstood, I have very little experience with Travis so I don't know if `~/.config/rebar3/rebar.config` can be edited elsewhere permanently.

`./rebar3 hex key list` should show you the key - https://www.rebar3.org/docs/hex-package-management#section-list-keys

From what I understand, this key and the Hex username are added as environment variables to Travis (`HEX_KEY` and `HEX_USERNAME` respectively) and the script then adds them to Travis's `~/.hex/hex.config`

**Comment by seriyps** [comment]
@andreineculau oh, you are right, I have access to Travis settings for jesse!
I see that the current publisher in hex is https://hex.pm/users/licenser . Should we try to contact him to ask for shared publisher rights?

**Comment by afhole** [comment]
> I see that the current publisher in hex is https://hex.pm/users/licenser . Should we try to contact him to ask for shared publisher rights?

@seriyps I had a brief email conversation with @licenser and he said he'd be happy to transfer ownership of the Hex package, if you email him I'm sure he can oblige

**Comment by Licenser** [comment]
More then happy to do it just let me know whom to add in a secret gist ( or this ticket ) so I can verify gh users :)

**Comment by andreineculau** [comment]
@licenser i guess that's me. Hit me

Regarding the key: "key list" only shows me the "names" of the keys (actually "rebar3 hex key generate" just adds new keys with undefined name") but no hexa string token as i would expect. Sorry for the lack of interest into hex and its quirks :)

**Comment by afhole** [comment]
@Licenser can you offer any pointers on how to retrieve `HEX_KEY` for Travis? Which credentials would you use, a personal user account e.g. @andreineculau's own account or something specific for Travis?

**Comment by afhole** [comment]
> Regarding the key: "key list" only shows me the "names" of the keys

Ah @andreineculau I think `rebar3 hex config key` is what you need

**Comment by afhole** [comment]
@andreineculau Looks like the Hex key can be an encrypted environment variable in Travis https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml

**Comment by andreineculau** [comment]
Yeah, i have lots of travis/ci experience but the problem as i see it is that i would have to share my one and only secret (that controls all packages that will be published to hex by my username?!) . I was hoping for a more granular control, otherwise we need some service account with hex.

**Comment by Licenser** [comment]
Sorry never used publishing via Travis, not sure where to start there

**Comment by Licenser** [comment]
@seriyps is now an owner of the packet, he can add/remove people as needed :)

**Comment by afhole** [comment]
Maybe for now at least Travis is overkill, I just picked up the extant PR and got rebar3 working - I have no idea what's best practice in this regard. Perhaps it is satisfactory to just push manually to Hex, and now that the Hex package ownership is in-house to the project it should be a lot simpler.

**Comment by afhole** [comment]
Where did we get to with this? Is it possible to update Hex manually with the latest release at least for now?

**Comment by seriyps** [comment]
@afhole Oh, sorry, I was on vacation. Seems current hex.pm version is 1.4.
I think I will publish 1.5.0, 1.5.1, 1.5.2, 1.5.3 one-by one and then will see what can be done to have auto-publishing finally working.

@Licenser thanks!

**Comment by seriyps** [comment]
ok, it seems it's not possible to publish to hex using git links in `deps` now. So, th3e new plan is to replace deps with hex links, tag 1.5.4 and publish just it for now.

**Comment by seriyps** [comment]
also, @afhole, it would be realy realy cool if you'll manage to split your PR to 2 parts: one to just migrate to rebar3 and 2nd one with all the changes related to hex.pm publishing.
Or I can do it based on your changes if you don't have time and is ok with me doing this.

**Comment by seriyps** [comment]
current jesse depends on @andreineculau 's fork of rfc3339. I think it's safe to update it to upstream https://hex.pm/packages/rfc3339 as well as jsx. I can do that.

**Comment by andreineculau** [comment]
@seriyps thanks for stepping in. Indeed my fork of rfc3339 is not needed (it has a fix for OTP 15, but currently we support=test only OTP 18+, so I'd say it's fine). I don't know of any other upstream issues.

I also agree with your split in 2 parts 👏 

PS: I have created a service account on hex.pm for the for-GET organization. I can share the credentials over keybase?! signal?! smth else?! and then we can add that user to own jesse/katt on hex.pm and create a token to use in travis. I have some time on my hands in the next weeks, so hopefully I can be of service once again and we can not just publish, but have this automated.

**Comment by seriyps** [comment]
regarding hex.pm publishing and deps - unfortunately, it might be tricky to update deps from git to hex deps without also doing all the upgrade-to-rebar3 work, because rebar2 does not support hex AFAIK. So, I either wait a bit more for @afhole to make a rebar3 migration or just do it myself.

Regarding hex.pm keys, I checked travis and I do see that there are secrets defined in env, but I can't see or edit them (but can delete and add new ones)
image
So, I think you can add your new keys to travis? Or you need to share them with me so I can add those keys as jesse owner in hex.pm? Looking at `rebar3 hex` docs, I can only add new package owners by email, not by key: https://www.rebar3.org/docs/hex-package-management#section-add-owner

**Comment by andreineculau** [comment]
> I checked travis and I do see that there are secrets defined in env, but I can't see or edit them (but can delete and add new ones)

right. you can see them, by triggering a debug build on travis and then printing the environment variables in the ssh session, but you cannot debug public repos, unless you request it via support https://docs.travis-ci.com/user/running-build-in-debug-mode/

hex.pm emails: andrei.neculau@gmail.com and andrei.neculau+forget@gmail.com (for-get service account). I will add the hex credentials to travis later today

**Comment by seriyps** [comment]
Great. I'm working on rebar3 port atm (should be done in a few hours). Will
add your emails to hex later today.

сб, 7 мар. 2020 г., 15:33 Andrei Neculau <notifications@github.com>:

**Comment by seriyps** [comment]
@andreineculau I've added your normal email, but I'm getting an error when trying to add `+forget` one:

```
DEBUG=1 rebar3 hex owner add jesse 'andrei.neculau+forget@gmail.com'                                                                                                                         [16:46:07]
===> Load global config file /home/seriy/.config/rebar3/rebar.config
===> 22.0.7 satisfies the requirement for minimum OTP version 18
===> Expanded command sequence to be run: []
===> Provider: {default,do}
===> Expanded command sequence to be run: [{hex,owner}]
===> Provider: {hex,owner}
Local Password:                         
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: {badmatch,
                             {error,
                              {rebar3_hex_owner,
                               {404,<<"jesse">>,
                                <<"andrei.neculau+forget@gmail.com">>}}}}
===> Stack trace to the error location:
[{rebar3_hex_owner,handle_command,2,
                   [{file,"/home/seriy/.cache/rebar3/plugins/rebar3_hex/src/rebar3_hex_owner.erl"},
                    {line,49}]},
 {rebar_core,do,2,
             [{file,"/home/seriy/workspace/rebar3/src/rebar_core.erl"},
              {line,154}]},
 {rebar_prv_do,do_task,5,
               [{file,"/home/seriy/workspace/rebar3/src/rebar_prv_do.erl"},
                {line,87}]},
 {rebar_core,do,2,
             [{file,"/home/seriy/workspace/rebar3/src/rebar_core.erl"},
              {line,154}]},
 {rebar3,run_aux,2,
         [{file,"/home/seriy/workspace/rebar3/src/rebar3.erl"},{line,182}]},
 {rebar3,main,1,
         [{file,"/home/seriy/workspace/rebar3/src/rebar3.erl"},{line,66}]},
 {escript,run,2,[{file,"escript.erl"},{line,758}]},
 {escript,start,1,[{file,"escript.erl"},{line,277}]}]
```

**Comment by seriyps** [comment]
Now given that rebar3 migration is already merged in #87 I think I will:

1. Bump version, tag a new release and publish it manually
2. Will wait a bit if @afhole would like to rebase this PR (travis-related part). If not, will do myself - hope it's ok.

**Comment by seriyps** [comment]
ok, so, I published 1.5.4.
Also on https://hex.pm/packages/jesse/1.5.4 and edocs on https://hexdocs.pm/jesse/1.5.4/

**Comment by afhole** [comment]
Hi @seriyps - thanks so much for this work. Sorry it's taken a ridiculously long time to reply! Please let me know if there is anything left that I can assist with.

**Comment by paulo-ferraz-oliveira** [comment]
There's no Travis CI any more, so this pull request is potentially in need of a major refactor.

**Comment by andreineculau** [comment]
better late than never. I've implemented publishing to hex.pm for github.com/for-get/katt (and tested it), and I've done the same for jsx.

Could you try again to add for-get as an owner, @seriyps ? Maybe try with `\+`, or since you get `404` (http code), try url-encoding it `%2B`? :) That should fix everything (tm).

PS: Most of the changes in this PR are in master. The rest could/should make their way in (e.g. `ct` target, `.rebar/BARE_MODE` -> `_build/BARE_MODE`, etc).

**Comment by andreineculau** [comment]
@seriyps i can see it works with username as well not just email. So try "for-get".
If not, use "andreineculau" or "andrei.neculau@gmail.com" as owner, and i will figure out smth.

https://hexdocs.pm/hex/Mix.Tasks.Hex.Owner.html

**Comment by seriyps** [comment]
@andreineculau sorry for delay. I added both `for-get` and `andrei.neculau@gmail.com` as owners

**Comment by andreineculau** [comment]
Brilliant 🎉

**Comment by andreineculau** [comment]
1.6.1 has been successfully published to hex.pm via Github Actions

I'll close this PR as I think all relevant changes have made it to `master`. Poke me if not. Or if you notice that something is off.

Last but not least - thank you to everyone involved!

**Pull request closed without merging**
